parameters:
  env(TURBOLINKS_ENABLED): false
  turbolinks.enabled: "%env(bool:TURBOLINKS_ENABLED)%"

  translator.class: "@Superrb\\KunstmaanAddonsBundle\\Service\\Translator"

services:
  kunstmaan_admin.versionchecker:
    class: Superrb\KunstmaanAddonsBundle\VersionCheck\VersionChecker
    arguments: ["@service_container", "@kunstmaan_admin.cache", "@translator"]
    public: true

  kunstmaan_addons.turbolinks_location_subscriber:
    class: Superrb\KunstmaanAddonsBundle\EventSubscriber\TurbolinksLocationSubscriber
    arguments:
      - "@request_stack"
      - "@session"
      - "%turbolinks.enabled%"
      - ['/^\/media/', '/^\/uploads/', '/^\/admin/']

    public: true
    tags:
      - "kernel.event_subscriber"

  placeholder_image_filter:
    class: Superrb\KunstmaanAddonsBundle\Service\PlaceholderImage
    tags:
      - { name: "liip_imagine.filter.loader", loader: placeholder_image }

  kunstmaan_addons.twig.extension:
    class: Superrb\KunstmaanAddonsBundle\Extension\TwigExtension
    arguments:
      $moneyRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\MoneyRenderer'
      $booleanRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\BooleanRenderer'
      $linkableEntityRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\LinkableEntityRenderer'
      $countryRenderer: '@Superrb\KunstmaanAddonsBundle\Renderer\CountryRenderer'
    tags:
      - "twig.extension"

  Superrb\KunstmaanAddonsBundle\Renderer\MoneyRenderer:
    public: true

  Superrb\KunstmaanAddonsBundle\Renderer\BooleanRenderer:
    public: true

  Superrb\KunstmaanAddonsBundle\Renderer\LinkableEntityRenderer:
    public: true
    arguments:
      $requestStack: '@Symfony\Component\HttpFoundation\RequestStack'
      $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
      $translator: '@Symfony\Contracts\Translation\TranslatorInterface'

  Superrb\KunstmaanAddonsBundle\Renderer\CountryRenderer:
    public: true
    arguments:
      $requestStack: '@Symfony\Component\HttpFoundation\RequestStack'

  Superrb\KunstmaanAddonsBundle\Service\MailerService:
    public: true
    arguments:
      $mailer: '@Symfony\Component\Mailer\MailerInterface'
      $templating: '@Twig\Environment'
      $translator: '@Symfony\Contracts\Translation\TranslatorInterface'
      $logger: '@Psr\Log\LoggerInterface'
      $emailFrom: "%enquiryfrom%"
      $emailBcc: "%enquirybcc%"

  Symfony\Contracts\Translation\TranslatorInterface: "@Superrb\\KunstmaanAddonsBundle\\Service\\Translator"
  Symfony\Component\Translation\TranslatorInterface: "@Superrb\\KunstmaanAddonsBundle\\Service\\Translator"
  kunstmaan_translator.service.translator.translator: "@Superrb\\KunstmaanAddonsBundle\\Service\\Translator"
  Superrb\KunstmaanAddonsBundle\Service\Translator:
    arguments:
      - "@service_container"
      - "@Superrb\\KunstmaanAddonsBundle\\Site"
      - "@translator.formatter.default"
      - "@Symfony\\Component\\HttpFoundation\\RequestStack"
      - "@kernel"
      - "@kunstmaan_translator.repository.translation"
      - "@kunstmaan_translator.service.translator.resource_cacher"
      - "%kernel.default_locale%"
      - {}
      - cache_dir: "%kuma_translator.cache_dir%"
        debug: "%kuma_translator.debug%"
      - "%kuma_translator.profiler%"
    tags: ["kernel.locale_aware"]

  Superrb\KunstmaanAddonsBundle\Site:
    arguments:
      $domainConfiguration: "@kunstmaan_multi_domain.domain_configuration"
      $allowedHosts: []
      $mailchimpListIds: []
      $emailSenders:
        default: "%enquiryfrom%"
      $googleAnalyticsIds: []
